# ==========================================================================
# BLACKLIST MANAGER - CRE PROJECT SETTINGS
# ==========================================================================

# ==========================================================================
# LOCAL SIMULATION TARGET
# ==========================================================================
local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://sepolia.gateway.tenderly.co/5srkjbJkFMoz8BH8ZiCmsH

# ==========================================================================
# STAGING TARGET
# ==========================================================================
staging-settings:
  account:
    workflow-owner-address: "0x89feEbA43b294425C0d7B482770eefbcc1359f8d"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://sepolia.gateway.tenderly.co/5srkjbJkFMoz8BH8ZiCmsH
