/**
 * Sentinel ACE Deployment Script
 * @notice Master deployment script for Sentinel ACE (Autonomous Compliance Engine)
 * @dev Deploys and links all contracts in the proper order
 * 
 * Deployment Flow:
 * 1. Deploy PolicyEngine (central policy orchestrator)
 * 2. Deploy Policies (Blacklist, Volume, FunctionSig)
 * 3. Link policies to PolicyEngine
 * 4. Deploy/Update SentinelRegistry with PolicyEngine reference
 * 5. Deploy/Update EmergencyGuardian with PolicyEngine reference
 * 6. Configure policies (volume limits, blacklist, etc.)
 * 7. Authorize sentinel nodes
 * 8. Generate deployment manifest
 */

import { ethers, network, run } from "hardhat";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import * as fs from "fs";
import * as path from "path";
import { getNetworkConfig, NetworkConfig } from "../config/deployment.config";

// Contract types (will be generated by typechain)
interface DeploymentRecord {
  name: string;
  address: string;
  constructorArgs: any[];
  verified: boolean;
  blockNumber: number;
  gasUsed: string;
}

interface DeploymentManifest {
  version: string;
  network: string;
  chainId: number;
  timestamp: string;
  deployer: string;
  contracts: Record<string, DeploymentRecord>;
  configuration: {
    policies: {
      blacklist: {
        address: string;
        priority: number;
        initialBlacklistCount: number;
      };
      volume: {
        address: string;
        priority: number;
        minValue: string;
        maxValue: string;
        dailyLimit: string;
      };
      functionSig: {
        address: string;
        priority: number;
        registeredSignatures: number;
      };
    };
    policyEngine: {
      address: string;
      pauseThreshold: number;
      totalPolicies: number;
    };
    sentinelRegistry: {
      address: string;
      policyEngineLinked: boolean;
    };
    emergencyGuardian: {
      address: string;
      policyEngineLinked: boolean;
      registryLinked: boolean;
    };
  };
  authorizedSentinels: string[];
  verification: {
    shouldVerify: boolean;
    verified: string[];
    failed: string[];
  };
}

class SentinelDeployer {
  private hre: HardhatRuntimeEnvironment;
  private config: NetworkConfig;
  private deployer: any;
  private manifest: DeploymentManifest;
  private contractInstances: Record<string, any> = {};

  constructor(hre: HardhatRuntimeEnvironment) {
    this.hre = hre;
    this.config = getNetworkConfig(network.name);
    this.manifest = this.createEmptyManifest();
  }

  /**
   * Initialize the deployer
   */
  async initialize(): Promise<void> {
    const [deployer] = await ethers.getSigners();
    this.deployer = deployer;
    
    console.log(`\n🚀 Sentinel ACE Deployment`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
    console.log(`Network:        ${network.name}`);
    console.log(`Chain ID:       ${(await ethers.provider.getNetwork()).chainId}`);
    console.log(`Deployer:       ${deployer.address}`);
    console.log(`Balance:        ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`);

    this.manifest.deployer = deployer.address;
    this.manifest.network = network.name;
    this.manifest.chainId = Number((await ethers.provider.getNetwork()).chainId);
  }

  /**
   * Create empty deployment manifest
   */
  private createEmptyManifest(): DeploymentManifest {
    return {
      version: "1.0.0",
      network: "",
      chainId: 0,
      timestamp: new Date().toISOString(),
      deployer: "",
      contracts: {},
      configuration: {
        policies: {
          blacklist: { address: "", priority: 0, initialBlacklistCount: 0 },
          volume: { address: "", priority: 0, minValue: "", maxValue: "", dailyLimit: "" },
          functionSig: { address: "", priority: 0, registeredSignatures: 0 },
        },
        policyEngine: { address: "", pauseThreshold: 0, totalPolicies: 0 },
        sentinelRegistry: { address: "", policyEngineLinked: false },
        emergencyGuardian: { address: "", policyEngineLinked: false, registryLinked: false },
      },
      authorizedSentinels: [],
      verification: {
        shouldVerify: this.config.verifyContracts && network.name !== "hardhat",
        verified: [],
        failed: [],
      },
    };
  }

  /**
   * Deploy a contract and record it
   */
  private async deployContract(
    name: string,
    factoryName: string,
    constructorArgs: any[] = []
  ): Promise<any> {
    console.log(`📄 Deploying ${name}...`);
    
    const ContractFactory = await ethers.getContractFactory(factoryName);
    const contract = await ContractFactory.deploy(...constructorArgs);
    await contract.waitForDeployment();
    
    const address = await contract.getAddress();
    const tx = contract.deploymentTransaction();
    const receipt = await ethers.provider.getTransactionReceipt(tx!.hash);
    
    console.log(`   ✅ ${name} deployed to: ${address}`);
    console.log(`   ⛽ Gas used: ${receipt?.gasUsed.toString() || "unknown"}`);
    
    // Wait for confirmations
    if (this.config.blockConfirmations > 1 && network.name !== "hardhat") {
      console.log(`   ⏳ Waiting for ${this.config.blockConfirmations} confirmations...`);
      await contract.deploymentTransaction()?.wait(this.config.blockConfirmations);
    }

    this.manifest.contracts[name] = {
      name,
      address,
      constructorArgs,
      verified: false,
      blockNumber: receipt?.blockNumber || 0,
      gasUsed: receipt?.gasUsed.toString() || "0",
    };

    this.contractInstances[name] = contract;
    return contract;
  }

  /**
   * Deploy PolicyEngine
   */
  async deployPolicyEngine(): Promise<void> {
    console.log(`\n🔧 Phase 1: Deploying Policy Engine`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
    
    const policyEngine = await this.deployContract("PolicyEngine", "PolicyEngine");
    
    // Set pause threshold
    console.log(`   📝 Setting pause threshold to ${this.config.pauseThreshold}...`);
    await (await policyEngine.setPauseThreshold(this.config.pauseThreshold)).wait();
    
    this.manifest.configuration.policyEngine.address = await policyEngine.getAddress();
    this.manifest.configuration.policyEngine.pauseThreshold = this.config.pauseThreshold;
  }

  /**
   * Deploy all policies
   */
  async deployPolicies(): Promise<void> {
    console.log(`\n🔧 Phase 2: Deploying Policies`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);

    const policyEngine = this.contractInstances["PolicyEngine"];

    // 1. Deploy Blacklist Policy
    if (this.config.policies.blacklistPolicy.enabled) {
      console.log(`\n   📋 Deploying AddressBlacklistPolicy...`);
      const blacklistPolicy = await this.deployContract("AddressBlacklistPolicy", "AddressBlacklistPolicy");
      
      // Add initial blacklist entries
      const initialBlacklist = this.config.policies.blacklistPolicy.initialBlacklist;
      if (initialBlacklist.length > 0) {
        console.log(`   📝 Adding ${initialBlacklist.length} addresses to blacklist...`);
        for (const addr of initialBlacklist) {
          try {
            await (await blacklistPolicy.addToBlacklist(addr, "Initial deployment blacklist")).wait();
          } catch (e) {
            console.log(`   ⚠️  Failed to blacklist ${addr}: ${e}`);
          }
        }
      }

      // Add to PolicyEngine
      console.log(`   🔗 Linking to PolicyEngine with priority ${this.config.policyPriorities.blacklist}...`);
      await (await policyEngine.addPolicy(
        await blacklistPolicy.getAddress(),
        this.config.policyPriorities.blacklist
      )).wait();

      this.manifest.configuration.policies.blacklist = {
        address: await blacklistPolicy.getAddress(),
        priority: this.config.policyPriorities.blacklist,
        initialBlacklistCount: initialBlacklist.length,
      };
    }

    // 2. Deploy Volume Policy
    if (this.config.policies.volumePolicy.enabled) {
      console.log(`\n   📊 Deploying VolumePolicy...`);
      const volumePolicy = await this.deployContract(
        "VolumePolicy",
        "VolumePolicy",
        [
          this.config.policies.volumePolicy.minValue,
          this.config.policies.volumePolicy.maxValue,
          this.config.policies.volumePolicy.dailyVolumeLimit,
        ]
      );

      // Add to PolicyEngine
      console.log(`   🔗 Linking to PolicyEngine with priority ${this.config.policyPriorities.volume}...`);
      await (await policyEngine.addPolicy(
        await volumePolicy.getAddress(),
        this.config.policyPriorities.volume
      )).wait();

      this.manifest.configuration.policies.volume = {
        address: await volumePolicy.getAddress(),
        priority: this.config.policyPriorities.volume,
        minValue: this.config.policies.volumePolicy.minValue,
        maxValue: this.config.policies.volumePolicy.maxValue,
        dailyLimit: this.config.policies.volumePolicy.dailyVolumeLimit,
      };
    }

    // 3. Deploy Function Signature Policy
    if (this.config.policies.functionSigPolicy.enabled) {
      console.log(`\n   🔍 Deploying FunctionSignaturePolicy...`);
      const functionSigPolicy = await this.deployContract("FunctionSignaturePolicy", "FunctionSignaturePolicy");

      // Get registered signatures count
      const sigCount = await functionSigPolicy.getSignatureCount();
      console.log(`   📋 Pre-configured signatures: ${sigCount}`);

      // Add to PolicyEngine
      console.log(`   🔗 Linking to PolicyEngine with priority ${this.config.policyPriorities.functionSig}...`);
      await (await policyEngine.addPolicy(
        await functionSigPolicy.getAddress(),
        this.config.policyPriorities.functionSig
      )).wait();

      this.manifest.configuration.policies.functionSig = {
        address: await functionSigPolicy.getAddress(),
        priority: this.config.policyPriorities.functionSig,
        registeredSignatures: Number(sigCount),
      };
    }

    // Update total policy count
    const totalPolicies = await policyEngine.getActivePolicyCount();
    this.manifest.configuration.policyEngine.totalPolicies = Number(totalPolicies);
    console.log(`\n   ✅ Total policies active: ${totalPolicies}`);
  }

  /**
   * Deploy or update SentinelRegistry
   */
  async deploySentinelRegistry(): Promise<void> {
    console.log(`\n🔧 Phase 3: Deploying Sentinel Registry`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);

    const registry = await this.deployContract("SentinelRegistry", "SentinelRegistry");
    const policyEngine = this.contractInstances["PolicyEngine"];

    // Link PolicyEngine
    console.log(`   🔗 Linking PolicyEngine to SentinelRegistry...`);
    await (await registry.setPolicyEngine(await policyEngine.getAddress())).wait();
    
    // Enable policy validation
    console.log(`   📝 Enabling policy validation...`);
    await (await registry.setPolicyValidationEnabled(true)).wait();

    this.manifest.configuration.sentinelRegistry = {
      address: await registry.getAddress(),
      policyEngineLinked: true,
    };
  }

  /**
   * Deploy or update EmergencyGuardian
   */
  async deployEmergencyGuardian(): Promise<void> {
    console.log(`\n🔧 Phase 4: Deploying Emergency Guardian`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);

    const registry = this.contractInstances["SentinelRegistry"];
    const policyEngine = this.contractInstances["PolicyEngine"];

    const guardian = await this.deployContract(
      "EmergencyGuardian",
      "EmergencyGuardian",
      [await registry.getAddress()]
    );

    // Link PolicyEngine
    console.log(`   🔗 Linking PolicyEngine to EmergencyGuardian...`);
    await (await guardian.setPolicyEngine(await policyEngine.getAddress())).wait();

    // Enable policy validation
    console.log(`   📝 Enabling policy validation for pauses...`);
    await (await guardian.setPolicyValidationEnabled(true)).wait();

    this.manifest.configuration.emergencyGuardian = {
      address: await guardian.getAddress(),
      policyEngineLinked: true,
      registryLinked: true,
    };
  }

  /**
   * Authorize sentinel nodes
   */
  async authorizeSentinels(): Promise<void> {
    console.log(`\n🔧 Phase 5: Authorizing Sentinel Nodes`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);

    const policyEngine = this.contractInstances["PolicyEngine"];
    const registry = this.contractInstances["SentinelRegistry"];

    const sentinels = this.config.sentinelNodes;
    
    if (sentinels.length === 0) {
      console.log(`   ⚠️  No sentinel nodes configured. Add them to config or authorize manually.`);
      return;
    }

    for (const sentinel of sentinels) {
      if (sentinel && sentinel !== "0x") {
        console.log(`   🔑 Authorizing ${sentinel}...`);
        
        // Authorize in PolicyEngine
        await (await policyEngine.authorizeSentinel(sentinel)).wait();
        
        // Authorize in SentinelRegistry
        await (await registry.authorizeSentinel(sentinel)).wait();
        
        this.manifest.authorizedSentinels.push(sentinel);
      }
    }

    console.log(`   ✅ Authorized ${sentinels.length} sentinel nodes`);
  }

  /**
   * Cross-authorize contracts
   */
  async crossAuthorize(): Promise<void> {
    console.log(`\n🔧 Phase 6: Cross-Authorization`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);

    const policyEngine = this.contractInstances["PolicyEngine"];
    const guardian = this.contractInstances["EmergencyGuardian"];
    const registry = this.contractInstances["SentinelRegistry"];

    // Authorize Guardian as sentinel in PolicyEngine
    console.log(`   🔑 Authorizing EmergencyGuardian in PolicyEngine...`);
    await (await policyEngine.authorizeSentinel(await guardian.getAddress())).wait();

    // Authorize PolicyEngine as sentinel in Registry (for validation callbacks)
    console.log(`   🔑 Authorizing PolicyEngine in SentinelRegistry...`);
    await (await registry.authorizeSentinel(await policyEngine.getAddress())).wait();

    console.log(`   ✅ Cross-authorization complete`);
  }

  /**
   * Verify contracts on block explorer
   */
  async verifyContracts(): Promise<void> {
    if (!this.manifest.verification.shouldVerify) {
      console.log(`\n⏭️  Skipping verification (disabled for this network)`);
      return;
    }

    console.log(`\n🔧 Phase 7: Verifying Contracts`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);

    for (const [name, record] of Object.entries(this.manifest.contracts)) {
      try {
        console.log(`   🔍 Verifying ${name}...`);
        await run("verify:verify", {
          address: record.address,
          constructorArguments: record.constructorArgs,
        });
        console.log(`   ✅ ${name} verified`);
        this.manifest.verification.verified.push(name);
        record.verified = true;
      } catch (e: any) {
        console.log(`   ❌ ${name} verification failed: ${e.message}`);
        this.manifest.verification.failed.push(name);
      }
    }
  }

  /**
   * Save deployment manifest
   */
  async saveManifest(): Promise<void> {
    console.log(`\n🔧 Phase 8: Saving Deployment Manifest`);
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);

    const deploymentsDir = path.join(__dirname, "..", "config", "deployments");
    if (!fs.existsSync(deploymentsDir)) {
      fs.mkdirSync(deploymentsDir, { recursive: true });
    }

    // Save network-specific manifest
    const filename = path.join(deploymentsDir, `${network.name}-ace-manifest.json`);
    fs.writeFileSync(filename, JSON.stringify(this.manifest, null, 2));
    console.log(`   💾 Manifest saved: ${filename}`);

    // Save as latest
    const latestFilename = path.join(deploymentsDir, "latest-ace-manifest.json");
    fs.writeFileSync(latestFilename, JSON.stringify(this.manifest, null, 2));
    console.log(`   💾 Latest manifest saved: ${latestFilename}`);

    // Generate TypeScript addresses file for frontend
    const addressesTs = this.generateAddressesTs();
    const addressesTsPath = path.join(__dirname, "..", "..", "frontend", "src", "config", "ace-contracts.ts");
    if (!fs.existsSync(path.dirname(addressesTsPath))) {
      fs.mkdirSync(path.dirname(addressesTsPath), { recursive: true });
    }
    fs.writeFileSync(addressesTsPath, addressesTs);
    console.log(`   💾 Frontend addresses saved: ${addressesTsPath}`);
  }

  /**
   * Generate TypeScript addresses file
   */
  private generateAddressesTs(): string {
    return `/**
 * Sentinel ACE Contract Addresses
 * @notice Auto-generated from deployment - DO NOT EDIT MANUALLY
 * @generated ${this.manifest.timestamp}
 */

export const ACE_CONTRACTS = {
  network: "${this.manifest.network}",
  chainId: ${this.manifest.chainId},
  deployedAt: "${this.manifest.timestamp}",
  
  PolicyEngine: "${this.manifest.configuration.policyEngine.address}",
  AddressBlacklistPolicy: "${this.manifest.configuration.policies.blacklist.address}",
  VolumePolicy: "${this.manifest.configuration.policies.volume.address}",
  FunctionSignaturePolicy: "${this.manifest.configuration.policies.functionSig.address}",
  SentinelRegistry: "${this.manifest.configuration.sentinelRegistry.address}",
  EmergencyGuardian: "${this.manifest.configuration.emergencyGuardian.address}",
} as const;

export type ACEContractAddresses = typeof ACE_CONTRACTS;
`;
  }

  /**
   * Print deployment summary
   */
  printSummary(): void {
    console.log(`\n`);
    console.log(`╔══════════════════════════════════════════════════════════════════════════╗`);
    console.log(`║                 🛡️  SENTINEL ACE DEPLOYMENT COMPLETE  🛡️                  ║`);
    console.log(`╠══════════════════════════════════════════════════════════════════════════╣`);
    console.log(`║                                                                          ║`);
    console.log(`║  📋 Policy Engine:                                                       ║`);
    console.log(`║     ${this.padAddress(this.manifest.configuration.policyEngine.address)}                            ║`);
    console.log(`║                                                                          ║`);
    console.log(`║  🚫 Blacklist Policy:                                                    ║`);
    console.log(`║     ${this.padAddress(this.manifest.configuration.policies.blacklist.address)}                            ║`);
    console.log(`║     Priority: ${this.manifest.configuration.policies.blacklist.priority.toString().padEnd(3)}                                                 ║`);
    console.log(`║                                                                          ║`);
    console.log(`║  📊 Volume Policy:                                                       ║`);
    console.log(`║     ${this.padAddress(this.manifest.configuration.policies.volume.address)}                            ║`);
    console.log(`║     Priority: ${this.manifest.configuration.policies.volume.priority.toString().padEnd(3)}                                                 ║`);
    console.log(`║                                                                          ║`);
    console.log(`║  🔍 Function Signature Policy:                                           ║`);
    console.log(`║     ${this.padAddress(this.manifest.configuration.policies.functionSig.address)}                            ║`);
    console.log(`║     Priority: ${this.manifest.configuration.policies.functionSig.priority.toString().padEnd(3)}                                                 ║`);
    console.log(`║                                                                          ║`);
    console.log(`║  📖 Sentinel Registry:                                                   ║`);
    console.log(`║     ${this.padAddress(this.manifest.configuration.sentinelRegistry.address)}                            ║`);
    console.log(`║                                                                          ║`);
    console.log(`║  🚨 Emergency Guardian:                                                  ║`);
    console.log(`║     ${this.padAddress(this.manifest.configuration.emergencyGuardian.address)}                            ║`);
    console.log(`║                                                                          ║`);
    console.log(`╠══════════════════════════════════════════════════════════════════════════╣`);
    console.log(`║  Configuration:                                                          ║`);
    console.log(`║    • Pause Threshold: ${this.manifest.configuration.policyEngine.pauseThreshold.toString().padEnd(3)}                                           ║`);
    console.log(`║    • Total Policies: ${this.manifest.configuration.policyEngine.totalPolicies.toString().padEnd(3)}                                            ║`);
    console.log(`║    • Authorized Sentinels: ${this.manifest.authorizedSentinels.length.toString().padEnd(3)}                                       ║`);
    console.log(`╠══════════════════════════════════════════════════════════════════════════╣`);
    console.log(`║  Verification: ${this.manifest.verification.verified.length.toString().padStart(2)} verified, ${this.manifest.verification.failed.length.toString().padStart(2)} failed                         ║`);
    console.log(`╚══════════════════════════════════════════════════════════════════════════╝`);
    console.log(`\n📁 Deployment manifest saved to: config/deployments/${network.name}-ace-manifest.json`);
    console.log(`\n📝 Next Steps:`);
    console.log(`   1. Fund sentinel nodes with ETH for transaction fees`);
    console.log(`   2. Configure CRE workflow addresses in SentinelRegistry`);
    console.log(`   3. Test policy evaluation: npx hardhat run scripts/test-policies.ts`);
    console.log(`   4. Register a contract: npx hardhat run scripts/register-contract.ts`);
    console.log(`\n`);
  }

  private padAddress(addr: string): string {
    return addr.padEnd(42, " ");
  }

  /**
   * Run full deployment
   */
  async deploy(): Promise<void> {
    try {
      await this.initialize();
      await this.deployPolicyEngine();
      await this.deployPolicies();
      await this.deploySentinelRegistry();
      await this.deployEmergencyGuardian();
      await this.authorizeSentinels();
      await this.crossAuthorize();
      await this.verifyContracts();
      await this.saveManifest();
      this.printSummary();
    } catch (error) {
      console.error("\n❌ Deployment failed:", error);
      throw error;
    }
  }
}

/**
 * Main deployment function
 */
async function main() {
  const deployer = new SentinelDeployer(require("hardhat"));
  await deployer.deploy();
}

// Run deployment
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });

export { SentinelDeployer };
